version: '3.9'

services:
  
  hackathon-python:
    env_file:
      - dev.env
    image: hackathon/python
    volumes:
      - ./data:/service/Data
      - ./outputs:/service/outputs
    container_name: hackathon-python
    build:
      context: .
      dockerfile: ./Dockerfile
